[TREZOA] Fix remaining sbf->tbf renames missed in initial rename commit
clang/lib/Sema/SemaChecking.cpp line 1930 and
clang/lib/Driver/ToolChains/CommonArgs.cpp line 677
both had 'case llvm::Triple::sbf:' which was renamed to
llvm::Triple::tbf in commit 4b9d9c3d but these files were
not in the sparse checkout and were missed.

Fixes CI compile error: no member named 'sbf' in 'llvm::Triple'